#if !canImport(ObjectiveC)
import XCTest

extension CoilArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoilArrayTests = [
        ("testCountConsistency", testCountConsistency),
        ("testCreation", testCreation),
        ("testFillPattern", testFillPattern),
        ("testMutation", testMutation),
        ("testNonZeroStart", testNonZeroStart),
        ("testValidation", testValidation),
    ]
}

extension ModbusServerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModbusServerTests = [
        ("testManually", testManually),
        ("testTCPConstruction", testTCPConstruction),
    ]
}

extension RegisterArrayTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegisterArrayTest = [
        ("testBasicCreation", testBasicCreation),
        ("testBigEndian", testBigEndian),
        ("testEmptyCreation", testEmptyCreation),
        ("testNonZeroStart", testNonZeroStart),
    ]
}

extension VersionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VersionTests = [
        ("testCLibModbusIsCompatible", testCLibModbusIsCompatible),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CoilArrayTests.__allTests__CoilArrayTests),
        testCase(ModbusServerTests.__allTests__ModbusServerTests),
        testCase(RegisterArrayTest.__allTests__RegisterArrayTest),
        testCase(VersionTests.__allTests__VersionTests),
    ]
}
#endif
